version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    day: saturday
    time: "03:00"
    timezone: Europe/Paris
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@babel/core"
    versions:
    - 7.12.13
    - 7.12.16
    - 7.12.17
    - 7.13.10
    - 7.13.14
    - 7.13.15
    - 7.13.8
  - dependency-name: webpack
    versions:
    - 5.17.0
    - 5.19.0
    - 5.21.0
    - 5.21.2
    - 5.23.0
    - 5.24.2
    - 5.24.3
    - 5.25.0
    - 5.27.0
    - 5.30.0
    - 5.31.2
  - dependency-name: css-loader
    versions:
    - 5.0.2
    - 5.1.0
    - 5.1.1
    - 5.1.2
    - 5.1.3
    - 5.2.1
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.12.13
    - 7.12.16
    - 7.12.17
    - 7.13.10
    - 7.13.12
    - 7.13.8
    - 7.13.9
  - dependency-name: "@nextcloud/browserslist-config"
    versions:
    - 2.0.0
  - dependency-name: webpack-cli
    versions:
    - 4.4.0
    - 4.5.0
  - dependency-name: marked
    versions:
    - 1.2.8
    - 1.2.9
