name: Lint

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  xml-linters:
    runs-on: ubuntu-latest

    name: info.xml lint
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Download schema
        run: wget https://apps.nextcloud.com/schema/apps/info.xsd

      - name: Lint info.xml
        uses: ChristophWurst/xmllint-action@v1
        with:
          xml-file: ./appinfo/info.xml
          xml-schema-file: ./info.xsd

